"""Stable v1 QuickUI preset codec and token resolver; standard library only."""
import json
from pathlib import Path
import re

CATALOG = json.loads((Path(__file__).resolve().parent / "presets/catalog.json").read_text())
OPTIONS = CATALOG["options"]


def defaults():
    return dict(CATALOG["defaults"])


def validate(config):
    if not isinstance(config, dict) or set(config) != {group["key"] for group in OPTIONS}:
        raise ValueError("Preset config must contain exactly the supported option keys")
    for group in OPTIONS:
        if not isinstance(config[group["key"]], str) or config[group["key"]] not in [v["value"] for v in group["values"]]:
            raise ValueError("Invalid preset option: " + group["key"])
    return config


def encode(config):
    validate(config)
    number, factor = 0, 1
    for group in OPTIONS:
        choices = [v["value"] for v in group["values"]]
        number += choices.index(config[group["key"]]) * factor
        factor *= len(choices)
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    result = ""
    while number:
        number, remainder = divmod(number, 36)
        result = digits[remainder] + result
    return "q1-" + (result or "0")


def decode(code):
    if not isinstance(code, str) or not re.fullmatch(r"q1-(0|[1-9a-z][0-9a-z]*)", code) or len(code) > 16:
        raise ValueError("Invalid or unsupported preset code; expected canonical q1-<base36>")
    number = int(code[3:], 36)
    config = {}
    for group in OPTIONS:
        choices = group["values"]
        number, index = divmod(number, len(choices))
        config[group["key"]] = choices[index]["value"]
    if number or encode(config) != code:
        raise ValueError("Preset code is outside the v1 option space")
    return config


def resolve(config, dark):
    validate(config)
    if type(dark) is not bool:
        raise ValueError("dark must be a boolean")
    mode = "dark" if dark else "light"
    tokens = dict(CATALOG["palettes"][config["palette"]][mode])
    accent = CATALOG["accents"][config["accent"]][mode]
    accent_fg = CATALOG["accentForeground"][mode]
    tokens.update(accent=accent, accentForeground=accent_fg,
                  destructive=CATALOG["destructive"][mode], destructiveForeground=accent_fg,
                  focus=accent, primary=accent, primaryForeground=accent_fg,
                  selection=accent if config["selection"] == "accent" else tokens["surfaceHover"],
                  selectionForeground=accent_fg if config["selection"] == "accent" else tokens["foreground"],
                  popup=tokens["surface"], popupForeground=tokens["foreground"],
                  card=tokens["surface"], cardForeground=tokens["foreground"],
                  dark=dark, fontFamily=CATALOG["fonts"][config["font"]], fontScale=1,
                  fontSize=13, smallFontSize=11, density=config["density"])
    tokens.update(CATALOG["densities"][config["density"]])
    radius = CATALOG["radii"][config["radius"]]
    tokens.update(radius=radius, radiusSmall=int(radius * .6 + .5), radiusLarge=int(radius * 1.4 + .5),
                  handleSize=18, borderWidth=CATALOG["borders"][config["border"]], focusWidth=2,
                  motionDuration=CATALOG["motions"][config["motion"]], disabledOpacity=.45)
    return tokens


def export(code):
    return {"schemaVersion": 1, "code": code, "config": decode(code)}


def import_config(data):
    if isinstance(data, dict) and "schemaVersion" in data:
        if set(data) != {"schemaVersion", "code", "config"} or type(data["schemaVersion"]) is not int or data["schemaVersion"] != 1:
            raise ValueError("Unsupported preset JSON envelope")
        if decode(data["code"]) != validate(data["config"]):
            raise ValueError("Preset JSON code does not match config")
        return data["config"]
    return validate(data)


def qml_theme(code):
    """Standalone sibling of Theme.qml; no runtime codec/catalog dependency."""
    config = decode(code)
    dark, light = resolve(config, True), resolve(config, False)
    lines = ["// Generated by QuickUI preset v1. Edit freely; the CLI will preserve edits.",
             "import QtQuick", "", "Theme {", "    readonly property string presetCode: " + json.dumps(code),
             "    property Theme systemTheme: null",
             "    readonly property bool followsHost: " + json.dumps(config["colorSource"] == "system") + " && systemTheme !== null"]
    for key, value in dark.items():
        if key == "dark":
            continue
        fallback = json.dumps(value) if value == light[key] else "(dark ? " + json.dumps(value) + " : " + json.dumps(light[key]) + ")"
        if isinstance(value, str) and value.startswith("#"):
            fallback = "followsHost ? systemTheme." + key + " : " + fallback
        lines.append("    " + key + ": " + fallback)
    header = (Path(__file__).resolve().parent / "registry/quickui/Theme.qml").read_text().split("import QtQuick", 1)[0]
    return (header + "\n".join(lines) + "\n}\n").encode()
